const DATA_ACTION_TYPE = {
  FETCH_BANNER_LIST: 'FETCH_BANNER_LIST',
  FETCH_ALBUM_LIST: 'FETCH_ALBUM_LIST',
  FETCH_HOT_TOPIC: 'FETCH_HOT_TOPIC',
  FETCH_NEW_SONG: 'FETCH_NEW_SONG',
  FETCH_SONG_LIST: 'FETCH_SONG_LIST',
  FETCH_SONG_RANKING: 'FETCH_SONG_RANKING',
  FETCH_TOP_SONG: 'FETCH_TOP_SONG',
  FETCH_VIDEO_LIST: 'FETCH_VIDEO_LIST',
};
const AUTH_ACTION_TYPE = {};

export { DATA_ACTION_TYPE, AUTH_ACTION_TYPE };
