import Head from 'next/head';
import React from 'react';

import Home from '../views/Home';

const HomePage = () => (
  <>
    <Head>
      <meta charSet="UTF-8" />
      <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="Generated by create next app" />
      <title>nhaccuatui</title>
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Home />
  </>
);
export default HomePage;
