// libs
import Head from 'next/head';
import React from 'react';
// layouts
import Home from '../views/Home';
// others
import mockData from '../api/mockApi';

export const getServerSideProps = async () => {
  // fetch data fake
  const data = { ...mockData };
  return {
    props: { ...data },
  };
};

const HomePage = (props) => {
  const {
    bannerList,
    albumList,
    hotTopic,
    newSong,
    songList,
    songRanking,
    topSong,
    videoList,
  } = props;
  return (
    <>
      <Head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <title>nhaccuatui</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home
        bannerList={bannerList}
        albumList={albumList}
        newSong={newSong}
        videoList={videoList}
        songList={songList}
        topSong={topSong}
        songRanking={songRanking}
        hotTopic={hotTopic}
      />
    </>
  );
};
export default HomePage;
