# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Storybook Project to GitHub Pages

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BASE_PATH: /nhaccuatui

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Get files
        uses: actions/checkout@v3
      - name: Install packages and Build project
        uses: borales/actions-yarn@v2.3.0
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          yarn build-storybook
          fi
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        run: |
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          npm run build-storybook
          fi
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: storybook-static
